### ISSUE TITLE
Co-parents-in-law partnership incorrect

### ISSUE THREAD

**Issue by jpretired** [hartenthaler/hh_extended_family#108] opened 2021-09-21 19:09 UTC
Partnership is displayed incorrectly **only with unlogged-in (anonymous) visitor**. It is OK with logged-in visitor (member, ...).
See screenshot:

![co-parents-in-law](https://user-images.githubusercontent.com/350656/134232716-d876af2a-d66c-4b3d-b538-71be22c716a7.jpg)

**Comment by hartenthaler** [comment] 2021-09-22 10:48
I have already seen this, but thought that it is only a bug in my development version. Thank you for reporting this!

**Comment by jpretired** [comment] 2021-09-23 06:41
I found the circumstances that bring about this issue.
They are:
1. In the family tree the privacy setting Show living individuals is set to Show to members.
2. The family tree is visited by an unlogged-in visitor.
3. There is a living individual in the family of proband's child whose parents-in-law (i.e. proband's co-parents-in-law) the module is seeking after.
Then we can see this 'Partnership families[$key]->fullName() ?>'.
I hope this may help.

**Comment by hartenthaler** [comment] 2021-09-23 15:40
It should be in this case "Partnership Private + Private" or "Child Private" if a family or a person cannot be shown.

I tried to reproduce the error, following your excellent analysis of the circumstances, but I was not successful. So I have to check this in more detail. Are you using the latest version of the module "extended family"?

**Comment by jpretired** [comment] 2021-09-23 16:36
Yes, 2.0.16.54:
![image](https://user-images.githubusercontent.com/350656/134547041-05831b92-b700-426a-8f45-d31a9eb03a36.png)

If you wish, have a look at my family tree pages:
Co-parents-in-law:
https://www.jprodina.cz/tree/nase-rodina/individual/I605/Josef-Prause#tab-_hh_extended_family_

Children-in-law:
https://www.jprodina.cz/tree/nase-rodina/individual/I201/Frantisek-Prause#tab-_hh_extended_family_

**Comment by hartenthaler** [comment] 2021-10-01 14:56
I Installed a fresh version of webtrees and Version 2.0.16.54 of the extended family module. Then I built up a test tree following your analysis. But I never saw your "`families[$key]->fullName() ?>`". But I can see the problem in your webtrees tree, so the problem exists.

The PHP code statement producing this is
`<h5><?= I18N::translate('Partnership') ?>&nbsp;<? $group->families[$key]->fullName() ?></h5>`
The first part with I18N and the intended space character is working correctly. The frame with `<h5>` and `</h5>` seems to work correctly. `$group->families[$key]->fullName()` should produce something like "Private + Private" but instead `$group->` is not interpreted correctly. Ok, there is a ">" character, but this should be ok and this working in many other cases perfectly.

Does anybody else observe this problem? Does anybody have any idea why this is not interpreted correctly?

**Comment by hartenthaler** [comment] 2021-10-01 15:31
will be fixed in next release

**Closed by hartenthaler** 2021-10-01 15:31 UTC
Labels: bug

**Comment by jpretired** [comment] 2021-10-01 17:26
GREAT!! Thank you very much! Was it difficult to find it?

Maybe you know that there are a few other similar buggy lines in file 'tab.phtml':
line 632, 700 and 702 with missing '=' sign after '<?'.

**Comment by hartenthaler** [comment] 2021-10-01 17:53
Yes. I looked at this point very often but didn't see it. My PHP version doesn't care about the missing "=", so I was not able to reproduce your issue. Finally, I have rewritten this part of the code and then I saw it.
Yes, when you know what is missing, it was easy to find all these lines.

**Comment by hartenthaler** [comment] 2021-10-02 15:33
You are right, it is not depending on the php-Version. Whether `<?` is working or not is depending on parameters in php.ini.
Thanks for your link!
